### ISSUE TITLE
Missing 'install' in pnpm dev command

### ISSUE THREAD

**Issue by a-gorczew** [sozonome/spoker#237]
### Describe the bug

There is missing `install` in `pnpm dev` command what causes issue on Windows 10 and RHEL 8.6:
```
pnpm dev

> spoker@1.16.14 dev /root/ago_tests/spoker-main
> next dev

sh: next: command not found
 ELIFECYCLE  Command failed.
```
Correct command seems like: `pnpm install dev` (it passed for me, however the installation failed on the next steps but it's different issue)

### Reproduction

Call 'pnpm dev' in the project root

### System Info

```Shell
Windows 10
RHEL 8.6 kernel: 4.18.0-372.32.1.el8_6.x86_64
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sozonome** [comment]
It's a standard to run install first before being able to run dev server. 

Hence, I'll update the readme to make it more clear

**Comment by a-gorczew** [comment]
Only one method provided in README to start anything doesn't work: https://github.com/sozonome/spoker?tab=readme-ov-file#getting-started. Any assumptions instead of clear instruction is not a good practice. Maybe just no one use it.

**Comment by sozonome** [comment]
Hi @a-gorczew , the readme actually has been updated to include pre-requisites https://github.com/sozonome/spoker#pre-requisites
